"""Add HealthRecord model

Revision ID: 86fe05b68335
Revises: 89f338c3df9f
Create Date: 2025-05-08 02:40:42.815795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86fe05b68335'
down_revision = '89f338c3df9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleep_hours', sa.Float(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('sleep')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleep', sa.FLOAT(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('sleep_hours')

    # ### end Alembic commands ###
