"""Add HealthRecord model

Revision ID: 89f338c3df9f
Revises: 8fec1e7faa66
Create Date: 2025-05-08 02:30:59.481213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f338c3df9f'
down_revision = '8fec1e7faa66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_record', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('steps',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sleep',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('mood',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_record', schema=None) as batch_op:
        batch_op.alter_column('mood',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sleep',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('steps',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
