"""Reset

<<<<<<<< HEAD:migrations/versions/6674901d52d7_reset.py
Revision ID: 6674901d52d7
Revises: 
Create Date: 2025-05-14 19:20:04.398173
========
Revision ID: 8cfd702d1051
Revises: 
Create Date: 2025-05-15 21:53:44.873517
>>>>>>>> share_part:migrations/versions/8cfd702d1051_initial_migration.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/6674901d52d7_reset.py
revision = '6674901d52d7'
========
revision = '8cfd702d1051'
>>>>>>>> share_part:migrations/versions/8cfd702d1051_initial_migration.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_record',
<<<<<<<< HEAD:migrations/versions/6674901d52d7_reset.py
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_data',
========
>>>>>>>> share_part:migrations/versions/8cfd702d1051_initial_migration.py
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personalized_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_by_user_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('shared_with_contact_email', sa.String(length=150), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shared_with_contact_email'], ['contact.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_data')
<<<<<<<< HEAD:migrations/versions/6674901d52d7_reset.py
    op.drop_table('uploaded_data')
========
    op.drop_table('personalized_message')
>>>>>>>> share_part:migrations/versions/8cfd702d1051_initial_migration.py
    op.drop_table('health_record')
    op.drop_table('contact')
    op.drop_table('user')
    # ### end Alembic commands ###
