"""Add HealthRecord table

Revision ID: 8fec1e7faa66
Revises: efe46465445d
Create Date: 2025-05-08 02:29:41.665829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fec1e7faa66'
down_revision = '7102e1b6eaa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('sleep', sa.Float(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('shared_at', sa.DateTime(), nullable=True))
        #batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        pass

    with op.batch_alter_table('uploaded_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=512), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_data', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    with op.batch_alter_table('shared_data', schema=None) as batch_op:
       # batch_op.drop_column('status')
        #batch_op.drop_column('shared_at')
        pass

    op.drop_table('health_record')
    # ### end Alembic commands ###
